function Result = fitSpectrum(Exp,Sys)

%==========================================================
% Universal radical fitting
%==========================================================

x0 = [ ...
    Sys.g ...
    Sys.A ...
    Sys.lwpp ...
    Sys.FieldShift ...
    Sys.Amplitude];

lb = [ ...
    Sys.g-0.003 ...
    Sys.A-10 ...
    0.02 ...
   -0.5 ...
    0.5];

ub = [ ...
    Sys.g+0.003 ...
    Sys.A+10 ...
    1.0 ...
    0.5 ...
    2.0];

options = optimoptions( ...
    'lsqcurvefit', ...
    'Display','iter', ...
    'Algorithm','trust-region-reflective', ...
    'MaxIterations',200, ...
    'MaxFunctionEvaluations',5000);

best = lsqcurvefit( ...
    @(p,x) simulateForFit(p,Exp,Sys), ...
    x0,...
    Exp.B,...
    Exp.signal,...
    lb,...
    ub,...
    options);

Calc = simulateForFit(best,Exp,Sys);

[RMS,R2,Similarity] = similarityScore(Exp.signal,Calc);

Result = struct();

Result.Name = Sys.Name;

Result.Sys = Sys;

Result.Sys.g = best(1);
Result.Sys.A = best(2);
Result.Sys.lwpp = best(3);

Result.FieldShift = best(4);
Result.Amplitude = best(5);

Result.B = Exp.B;
Result.Signal = Calc;

Result.RMS = RMS;
Result.R2 = R2;
Result.Similarity = Similarity;

Result.Parameters = table( ...
    best(1),...
    best(2),...
    best(3),...
    best(4),...
    best(5),...
    'VariableNames',...
    {'g','A_MHz','lwpp','FieldShift','Amplitude'});

end
