function Result = fitTEMPOL(Exp, Sys)

%==========================================================
% Automatic fitting of TEMPOL spectrum
%
% Optimized parameters:
% p(1) = g
% p(2) = A (MHz)
% p(3) = lwpp (mT)
% p(4) = Field Shift (mT)
% p(5) = Amplitude
%==========================================================

%% Initial parameters

x0 = [ ...
    Sys.g ...
    Sys.A ...
    Sys.lwpp ...
    Sys.FieldShift ...
    Sys.Amplitude];

%% Lower bounds

lb = [ ...
    2.0040 ...
    40.0 ...
    0.02 ...
   -0.50 ...
    0.50];

%% Upper bounds

ub = [ ...
    2.0080 ...
    55.0 ...
    1.00 ...
     0.50 ...
     2.00];

%% Optimization options

options = optimoptions('lsqcurvefit', ...
    'Display','iter', ...
    'Algorithm','trust-region-reflective', ...
    'MaxIterations',200, ...
    'MaxFunctionEvaluations',5000, ...
    'FunctionTolerance',1e-10, ...
    'StepTolerance',1e-10);

%% Optimization

best = lsqcurvefit( ...
    @(p,x) simulateForFit(p,Exp), ...
    x0, ...
    Exp.B, ...
    Exp.signal, ...
    lb, ...
    ub, ...
    options);

%% Final simulated spectrum

Calc = simulateForFit(best,Exp);

%% Fit statistics

[RMS,R2,Similarity] = similarityScore(Exp.signal,Calc);

%% Save result

Result = struct();

Result.Name = Sys.Name;

Result.g = best(1);
Result.A = best(2);
Result.lwpp = best(3);
Result.shift = best(4);
Result.amplitude = best(5);

Result.B = Exp.B;
Result.Signal = Calc;

Result.RMS = RMS;
Result.R2 = R2;
Result.Similarity = Similarity;

Result.Parameters = table( ...
    Result.g,...
    Result.A,...
    Result.lwpp,...
    Result.shift,...
    Result.amplitude,...
    'VariableNames',{'g','A_MHz','LineWidth_mT','FieldShift_mT','Amplitude'});

End
