function plotComparison(Exp,Result)
%==============================================================
% plotComparison
%
% Displays experimental spectrum, fitted spectrum
% and residual.
%==============================================================

figure( ...
    'Name','SpinFit PoC', ...
    'Color','w', ...
    'NumberTitle','off', ...
    'Position',[100 100 1100 700]);

%% Residual

Residual = Exp.Signal - Result.Signal;

%% ============================================================
% Spectrum
%% ============================================================

subplot(2,1,1)

plot(Exp.Field,Exp.Signal,...
    'k','LineWidth',1.5);

hold on

plot(Result.Field,...
     Result.Signal,...
     'r','LineWidth',1.5);

grid on
box on

xlabel('Magnetic field (mT)')
ylabel('Normalized intensity')

title(sprintf('%s    Similarity = %.2f %%', ...
    char(Result.Name), ...
    Result.Similarity));

legend( ...
    'Experiment', ...
    'Fit', ...
    'Location','best');

%% ============================================================
% Residual
%% ============================================================

subplot(2,1,2)

plot(Exp.Field,...
    Residual,...
    'b','LineWidth',1.2);

hold on

yline(0,'k--');

grid on
box on

xlabel('Magnetic field (mT)')
ylabel('Residual')

title(sprintf( ...
    'Residual    RMS = %.5f     R^2 = %.4f', ...
    Result.RMS,...
    Result.R2));

%% ============================================================
% Information
%% ============================================================

txt = sprintf([ ...
'Radical: %s\n' ...
'\n' ...
'Similarity : %.2f %%\n' ...
'RMS        : %.6f\n' ...
'R²         : %.6f\n' ...
'\n' ...
'g          : %s\n' ...
'A (MHz)    : %s\n' ...
'Line width : %.4f mT\n' ...
'Shift      : %.4f mT\n' ...
'Amplitude  : %.3f'], ...
char(Result.Name), ...
Result.Similarity, ...
Result.RMS, ...
Result.R2, ...
mat2str(Result.g,6), ...
mat2str(Result.A,6), ...
Result.lwpp, ...
Result.shift, ...
Result.amplitude);

annotation( ...
    'textbox', ...
    [0.70 0.58 0.26 0.30], ...
    'String',txt, ...
    'Interpreter','none', ...
    'FitBoxToText','on', ...
    'BackgroundColor','white', ...
    'EdgeColor',[0.5 0.5 0.5], ...
    'FontName','Consolas', ...
    'FontSize',10);

end

