function plotComparison(Exp, Result)

%==========================================================
% Plot experimental and fitted spectra
%==========================================================

figure( ...
    'Name','SpinFit PoC', ...
    'Color','w', ...
    'NumberTitle','off', ...
    'Position',[100 100 1000 700]);

%% Residual

Residual = Exp.signal - Result.Signal;

%% -------------------------------------------------------
% Experimental vs Fitted
%--------------------------------------------------------

subplot(2,1,1)

plot(Exp.B, Exp.signal, ...
    'k', ...
    'LineWidth',1.5);

hold on

plot(Result.B, Result.Signal, ...
    'r', ...
    'LineWidth',1.5);

grid on
box on

xlabel('Magnetic Field (mT)');
ylabel('Normalized Intensity');

title(sprintf('%s    Similarity = %.2f %%', ...
    Result.Name, ...
    Result.Similarity));

legend( ...
    'Experiment', ...
    'Simulation', ...
    'Location','best');

%% -------------------------------------------------------
% Residual
%--------------------------------------------------------

subplot(2,1,2)

plot(Exp.B, Residual, ...
    'b', ...
    'LineWidth',1.2);

hold on

yline(0,'k--');

grid on
box on

xlabel('Magnetic Field (mT)');
ylabel('Residual');

title(sprintf('Residual   RMS = %.6f   R^2 = %.6f', ...
    Result.RMS, ...
    Result.R2));

%% -------------------------------------------------------
% Information panel
%--------------------------------------------------------

annotation( ...
    'textbox', ...
    [0.69 0.63 0.28 0.28], ...
    'String', { ...
        ['Radical: ', Result.Name], ...
        ['Similarity: ', sprintf('%.2f %%',Result.Similarity)], ...
        '', ...
        ['g = ', mat2str(Result.g,6)], ...
        ['A = ', mat2str(Result.A,6), ' MHz'], ...
        ['Line Width = ', sprintf('%.3f mT',Result.lwpp)], ...
        ['Field Shift = ', sprintf('%.4f mT',Result.shift)], ...
        ['Amplitude = ', sprintf('%.3f',Result.amplitude)], ...
        '', ...
        ['RMS = ', sprintf('%.6f',Result.RMS)], ...
        ['R^2 = ', sprintf('%.6f',Result.R2)] ...
    }, ...
    'FitBoxToText','on', ...
    'BackgroundColor','white', ...
    'EdgeColor',[0.6 0.6 0.6], ...
    'FontName','Consolas', ...
    'FontSize',10);

end
